# Generated by Django 5.2.5 on 2025-08-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabUsuarioCadastrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('idade', models.PositiveIntegerField()),
                ('dt_nascimento', models.DateField()),
                ('raca', models.CharField(choices=[('preto', 'Preto'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('pardo', 'Pardo')], max_length=15)),
                ('formacao', models.CharField(choices=[('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('curso_tecnico', 'Curso Técnico'), ('pos_graduacao', 'Pós Gradução')], max_length=180)),
            ],
            options={
                'db_table': '[DJANGO].[TAB_USUARIOS_CADASTRADOS]',
            },
        ),
    ]
