# Generated by Django 5.2.5 on 2025-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_forms_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabusuariocadastrados',
            name='arquivo',
            field=models.FileField(null=True, upload_to='arquivos/'),
        ),
    ]
